# Generated by Django 4.2.6 on 2023-10-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ref',
            old_name='company',
            new_name='connection',
        ),
        migrations.AddField(
            model_name='ref',
            name='surname',
            field=models.CharField(default='SURNAME', max_length=200),
        ),
    ]
