# Generated by Django 4.2.6 on 2023-10-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_ref_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ref',
            name='profile_picture',
        ),
    ]
