# Generated by Django 4.2.6 on 2023-10-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_image_delete_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
