# Generated by Django 4.2.6 on 2023-10-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0010_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='ref',
            name='image',
            field=models.ImageField(blank=True, upload_to='Users/madinadairova/Documents/my_website/backend/media'),
        ),
    ]
