# Generated by Django 4.2.6 on 2023-10-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0012_ref_email_adress_ref_linkedin_url_alter_ref_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref',
            name='name',
            field=models.CharField(default='NAME', max_length=200),
        ),
    ]
