# Generated by Django 4.2.6 on 2023-10-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0013_alter_ref_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
