# Generated by Django 4.2.6 on 2023-10-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0014_alter_ref_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
